### ISSUE TITLE
Modle的set方法导致修改数据不正确

### ISSUE THREAD

**Issue by yyan** [jayqqaa12/jbase#1]
当我修改数据的时候，将输入框内容清空，这个空数据无法更新到数据库。

**Comment by jayqqaa12** [comment]
好的 添加了 一个setNull 方法 可满足你的需求 更新一下

**Comment by yyan** [comment]
我认为添加这个方法不妥，增加了使用的复杂度。如果不覆盖set方法是否更好一点呢？

**Comment by jayqqaa12** [comment]
使用场景不同  不判断的话 如果不想为null 的时候 要提前做判断一下
